### ISSUE TITLE
Libfaiss error

### ISSUE THREAD

**Issue by nxj** [CannyLab/tsne-cuda#6] opened 2018-08-07 05:38 UTC
Hi,

i get the following error during run time:
OSError: libfaiss.so: cannot open shared object file: No such file or directory

Even after a manual install of FAISS. Any idea why this is happening?

**Comment by DavidMChan** [comment] 2018-08-07 15:15
What OS/configuration are you using? Are you installing from source, or using the pip packages? 

It seems like FAISS may not be on your library loading path - you can often fix this by using "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path to FAISS>", however it's difficult to provide help without a bit more information because this problem is closely tied to your system configuration.

**Comment by nxj** [comment] 2018-08-08 06:14
Thank you, got it fixed by exporting the correct LD_LIBRARY_PATH. But still needed to install FAISS from source as the conda version does not provide a libfaiss.so. Maybe it would be possible to include FAISS in the pip wheel / use the conda installed FAISS library? This would make usage a bit easier.

**Comment by DavidMChan** [comment] 2018-08-08 14:45
Agreed, That's something that we're looking into as a potential extension to what we have - however it's a little bit tricky, as I'm not entirely sure given the FAISS license we can distribute a binary version - so including the binary in the pip wheel is questionable. I think that it's possible to get it working with conda - however our group has limited experience with packaging for conda, so it might take a bit (right now installing from conda just pulls the pypi package).

**Comment by ktamiola** [comment] 2018-08-10 12:49
@nxj suggestion is very good!

**Comment by DavidMChan** [comment] 2018-08-14 15:42
Duplicate of #9

**Closed by DavidMChan** 2018-08-14 15:42 UTC
Labels: enhancement
