### ISSUE TITLE
undefined symbol: _ZN5faiss14FaissExcepttionC1ERKSsPKcS4_i

### ISSUE THREAD

**Issue by LeZhengThu** [CannyLab/tsne-cuda#16] opened 2018-08-30 18:27 UTC
I can install tsne-cuda using "pip install tsnecuda" and import it correctly. But when I want to test the installation by "tsnecuda.test()", it raises an error "module object has no attribute test".

**Comment by DavidMChan** [comment] 2018-08-30 18:30
There are currently no meaningful tests (See #10 ) - We're working on supporting them, but because of the stochasticity of the program, testing correctness is difficult, while testing functionality is trivial. Consider testing/validating your installation by running the MNIST dataset.

**Comment by LeZhengThu** [comment] 2018-08-30 18:36
Then the wiki is misleading and should be revised. 
In addition, I did a quick test using the example code, it also raised an error.
![image](https://user-images.githubusercontent.com/18341929/44871882-f4d4a700-ac48-11e8-9010-9dddc228ab60.png)

**Comment by DavidMChan** [comment] 2018-08-30 18:40
The wiki has already been resolved - Please see [Basic usage](https://github.com/CannyLab/tsne-cuda/wiki/Basic-Usage:-Python)

In your case, you should have `from tsnecuda import TSNE` instead of `import tsnecuda as TSNE`

**Comment by LeZhengThu** [comment] 2018-08-30 18:46
@DavidMChan Thanks. 
A new error came out as "OSError: libfaiss.so: cannot open shared object file: No such file or directory."

**Comment by DavidMChan** [comment] 2018-08-30 18:57
See: https://github.com/facebookresearch/faiss/blob/master/INSTALL.md To install FAISS, Facebook Research's GPU-based ANN query library. Also see #6

**Comment by LeZhengThu** [comment] 2018-08-30 22:35
@DavidMChan  Thanks.
A new error came out as "~/python2.7/site-packages/tsnecuda/libtsnecuda.so: undefined symbol: _ZN5faiss14FaissExcepttionC1ERKSsPKcS4_i". Did this tell me that faiss was not installed correctly? Besides, in #6 you wrote "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:", what was the exact path for this? Thanks.

**Comment by rmrao** [comment] 2018-08-31 00:00
Could you provide your platform details? If ‘libfaiss.so’ is found but it’s getting undefined symbols, I doubt it’s an issue with LD_LIBRARY_PATH. You can double check this by ensuring that libfaiss.so is on the path by setting `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path_to_libfaiss>`.

Alternatively, we’re currently working on a conda install which will hopefully be ready in the next week or so.

**Comment by cmartinezfleites** [comment] 2018-09-04 15:01
Hi,

I have the same issue:
OS: linux
python: error appears with both 3.6 AN 2.7. 
faiss was built from sources and libraries are in the path.
tsnecuda was installed using pip.

error:

(py27) -bash-4.2$ python
Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from tsnecuda import TSNE
>>> X_embedded = TSNE(n_components=2, perplexity=15, learning_rate=10).fit_transform(X)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/CGT/Software/Anaconda/envs/py27/lib/python2.7/site-packages/tsnecuda/TSNE.py", line 110, in __init__
    self._lib = N.ctypeslib.load_library('libtsnecuda', self._path) # Load the ctypes library
  File "/CGT/Software/Anaconda/envs/py27/lib/python2.7/site-packages/numpy/ctypeslib.py", line 150, in load_library
    return ctypes.cdll[libpath]
  File "/CGT/Software/Anaconda/envs/py27/lib/python2.7/ctypes/__init__.py", line 441, in __getitem__
    return getattr(self, name)
  File "/CGT/Software/Anaconda/envs/py27/lib/python2.7/ctypes/__init__.py", line 436, in __getattr__
    dll = self._dlltype(name)
  File "/CGT/Software/Anaconda/envs/py27/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /CGT/Software/Anaconda/envs/py27/lib/python2.7/site-packages/tsnecuda/libtsnecuda.so: undefined symbol: _ZN5faiss14FaissExceptionC1ERKSsPKcS4_i

-----------------
when ldd -r  libtsnecuda.so :

(py27) -bash-4.2$ ldd -r /CGT/Software/Anaconda/envs/py27/lib/python2.7/site-packages/tsnecuda/libtsnecuda.so
        linux-vdso.so.1 =>  (0x00007ffcb1eb3000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fbc84935000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fbc84731000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fbc84529000)
        libfaiss.so => /CGT/Software/faiss_lib/libfaiss.so (0x00007fbc84236000)
        libcublas.so.9.0 => /CGT/Software/Anaconda/envs/tensorflow/lib/libcublas.so.9.0 (0x00007fbc80dfd000)
        libcusparse.so.9.0 => /CGT/Software/Anaconda/envs/tensorflow/lib/libcusparse.so.9.0 (0x00007fbc7d692000)
        libstdc++.so.6 => /CGT/Software/Anaconda/lib/libstdc++.so.6 (0x00007fbc7d358000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fbc7d056000)
        libgcc_s.so.1 => /CGT/Software/Anaconda/lib/libgcc_s.so.1 (0x00007fbc7ce44000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fbc7ca77000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fbc86847000)
        libopenblas.so.0 => /CGT/Software/Anaconda/envs/tensorflow/lib/libopenblas.so.0 (0x00007fbc7ba34000)
        libgomp.so.1 => /CGT/Software/Anaconda/envs/tensorflow/lib/libgomp.so.1 (0x00007fbc86a18000)
        libgfortran.so.3 => /CGT/Software/Anaconda/envs/tensorflow/lib/./libgfortran.so.3 (0x00007fbc7b72b000)
undefined symbol: _ZN5faiss14FaissExceptionC1ERKSsPKcS4_i       (/CGT/Software/Anaconda/envs/py27/lib/python2.7/site-packages/tsnecuda/libtsnecuda.so)
undefined symbol: _ZNK5faiss14ParameterSpace19set_index_parameterEPNS_5IndexERKSsd      (/CGT/Software/Anaconda/envs/py27/lib/python2.7/site-packages/tsnecuda/libtsnecuda.so)

Any suggestion?

**Comment by DavidMChan** [comment] 2018-09-04 15:11
I believe that this latest issue occurs when building a newer version of FAISS than the tsnecuda binaries in pip were built with.  The latest tested version of FAISS tested with tsnecuda is 431545ee2b00f19d0a0407be32b7ad3cbd6fc188, (See: https://github.com/facebookresearch/faiss/commits/431545ee2b00f19d0a0407be32b7ad3cbd6fc188). 

We will work to update the libraries - however because both FAISS and this library are, at their core, research code - they are evolving relatively quickly, and it can be hard to keep up. The best way to ensure that the code compiles and runs correctly is by building tsnecuda and FAISS directly from source using our git submodules - which make sure the versioning is correct.

**Comment by cmartinezfleites** [comment] 2018-09-05 10:11
Hi,
Indeed, when this FAISS source version is used the issue goes away.

Now, I seem to have the same problem as in Critical Execution Error #11, so I am trying to build tsnecuda.

 Despite having MKL available, although not in the standard location, the configuration step fails with:

>echo $MKLROOT
/CGT/Software/intel/MKL/compilers_and_libraries_2018.3.222/linux/mkl

>cmake --DMKL_DIR=/CGT/Software/intel/MKL/compilers_and_libraries_2018.3.222/linux/mkl/ ../
-- Not building with ZMQ. Interactive visualization disabled. To build with ZMQ use -DWITH_ZMQ=ON
-- Not building standalone gpufaiss lib. To build gpufaiss standalone use -DWITH_FAISS_GPU_STANDALONE=ON
CMake Warning (dev) at cmake/Modules/FindMKL.cmake:198 (LINK_DIRECTORIES):
  This command specifies the relative path

    MKL_ROOT_DIR-NOTFOUND/lib/intel64

  as a link directory.

  Policy CMP0015 is not set: link_directories() treats paths relative to the
  source dir.  Run "cmake --help-policy CMP0015" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
  CMakeLists.txt:84 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find MKL (missing: MKL_INCLUDE_DIR MKL_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindMKL.cmake:201 (find_package_handle_standard_args)
  CMakeLists.txt:84 (find_package)


-- Configuring incomplete, errors occurred!
See also "/CGT/Software/tsne-cuda/build/CMakeFiles/CMakeOutput.log".

Any suggestion?


I also have openblas in the path, but when:
> cmake -WITH_MKL=FALSE ../
-- Not building with ZMQ. Interactive visualization disabled. To build with ZMQ use -DWITH_ZMQ=ON
-- Not building standalone gpufaiss lib. To build gpufaiss standalone use -DWITH_FAISS_GPU_STANDALONE=ON
CMake Warning (dev) at cmake/Modules/FindMKL.cmake:198 (LINK_DIRECTORIES):
  This command specifies the relative path

    MKL_ROOT_DIR-NOTFOUND/lib/intel64

  as a link directory.

  Policy CMP0015 is not set: link_directories() treats paths relative to the
  source dir.  Run "cmake --help-policy CMP0015" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
  CMakeLists.txt:84 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find MKL (missing: MKL_INCLUDE_DIR MKL_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindMKL.cmake:201 (find_package_handle_standard_args)
  CMakeLists.txt:84 (find_package)


-- Configuring incomplete, errors occurred!
See also "/CGT/Software/tsne-cuda/build/CMakeFiles/CMakeOutput.log".

Is there a way to give the location of openblas library?

**Comment by cmartinezfleites** [comment] 2018-09-05 12:32
Hi,

the issue of finding MKL is resolved by using a different version of cmake/Module/FindMKL.cmake, in my case:
github:   scivision/FindMKL.cmake

Now, compilation with MKL 2018 produces:

[ 40%] Building NVCC (Device) object CMakeFiles/tsne_test.dir/third_party/faiss/gpu/utils/nvidia/./tsne_test_generated_fp16_emu.cu.o
/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(277): error: name followed by "::" must be a class or namespace name

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(277): error: expected a ";"

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(278): error: identifier "opt" is undefined

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(284): error: name followed by "::" must be a class or namespace name

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(330): error: name followed by "::" must be a class or namespace name

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(330): error: expected a ";"

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(331): error: identifier "opt" is undefined

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(337): error: name followed by "::" must be a class or namespace name

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(365): error: name followed by "::" must be a class or namespace name

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(365): error: expected a ";"

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(366): error: identifier "opt" is undefined

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(372): error: name followed by "::" must be a class or namespace name

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(407): error: name followed by "::" must be a class or namespace name

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(407): error: expected a ";"

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(408): error: identifier "opt" is undefined

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(414): error: name followed by "::" must be a class or namespace name

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(389): warning: variable "num_columns" was declared but never referenced

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(390): warning: variable "num_rows" was declared but never referenced

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(391): warning: variable "num_channels" was declared but never referenced

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(449): error: name followed by "::" must be a class or namespace name

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(449): error: expected a ";"

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(450): error: identifier "opt" is undefined

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(456): error: name followed by "::" must be a class or namespace name

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(431): warning: variable "num_columns" was declared but never referenced

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(432): warning: variable "num_rows" was declared but never referenced

/CGT/Software/tsne-cuda/src/include/test/test_tsne.h(433): warning: variable "num_channels" was declared but never referenced

20 errors detected in the compilation of "/tmp/tmpxft_0000bdee_00000000-8_test.compute_70.cpp1.ii".
CMake Error at tsne_test_generated_test.cu.o.cmake:260 (message):
  Error generating file
  /CGT/Software/tsne-cuda/build/CMakeFiles/tsne_test.dir/src/test/./tsne_test_generated_test.cu.o


make[2]: *** [CMakeFiles/tsne_test.dir/src/test/./tsne_test_generated_test.cu.o] Error 1

make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/tsne_test.dir/all] Error 2
Scanning dependencies of target tsnecuda
[ 40%] [ 41%] [ 41%] [ 41%] [ 41%] [ 41%] [ 41%] [ 42%] [ 42%] [ 43%] [ 43%] [ 43%] Building CXX object CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/GpuAutoTune.cpp.o
Building CXX object CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/utils/StackDeviceMemory.cpp.o
Building CXX object CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/utils/MemorySpace.cpp.o
Building CXX object CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/utils/DeviceMemory.cpp.o
Building CXX object CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/StandardGpuResources.cpp.o
Building CXX object CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/utils/Timer.cpp.o
Building CXX object CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/GpuResources.cpp.o
Building CXX object CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/impl/RemapIndices.cpp.o
Building CXX object CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/GpuClonerOptions.cpp.o
Building CXX object CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/IndexProxy.cpp.o
Building CXX object CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/utils/WorkerThread.cpp.o
Building CXX object CMakeFiles/tsnecuda.dir/third_party/faiss/gpu/utils/DeviceUtils.cpp.o
Linking CXX shared library libtsnecuda.so
[ 43%] Built target tsnecuda
make: *** [all] Error 2

is there an issue with the MKL version I have?

Many thanks,
cmartinezfleites

**Comment by cmartinezfleites** [comment] 2018-09-05 12:43
adding to the message above:

>ldd -r libtsnecuda.so
        linux-vdso.so.1 =>  (0x00007ffed7020000)
        libcudart.so.9.1 => /usr/local/cuda/lib64/libcudart.so.9.1 (0x00007efe1215c000)
        libfaiss.so => /CGT/Software/tsne-cuda/build/lib/libfaiss.so (0x00007efe10e80000)
        libcublas.so.9.1 => /usr/local/cuda/lib64/libcublas.so.9.1 (0x00007efe0d8e9000)
        libcusparse.so.9.1 => /usr/local/cuda/lib64/libcusparse.so.9.1 (0x00007efe0a215000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007efe09ff9000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007efe09cf2000)
        libm.so.6 => /lib64/libm.so.6 (0x00007efe099f0000)
        libgomp.so.1 => /lib64/libgomp.so.1 (0x00007efe097ca000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007efe095b4000)
        libc.so.6 => /lib64/libc.so.6 (0x00007efe091e7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007efe15d53000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007efe08fe3000)
        librt.so.1 => /lib64/librt.so.1 (0x00007efe08ddb000)
undefined symbol: mkl_trans_mkl_somatcopy2_par  (./libtsnecuda.so)
undefined symbol: mkl_blas_daxpy        (./libtsnecuda.so)
undefined symbol: mkl_blas_saxpy        (./libtsnecuda.so)
undefined symbol: mkl_lapack_dlaeh2     (./libtsnecuda.so)
undefined symbol: mkl_lapack_dsbrdbn    (./libtsnecuda.so)
undefined symbol: mkl_lapack_dlatrd     (./libtsnecuda.so)

**Comment by DavidMChan** [comment] 2018-09-05 15:45
The issue above is actually caused by trying to compile the tests - which don't compile as of now (see #10). Can you confirm that -DBUILD_TEST=FALSE in your compilation stack?

**Comment by cmartinezfleites** [comment] 2018-09-05 16:02
Hi,

the three changes allow compilation in my case:

1) no compile tests 
2) I had an older version of cmake, once updated, I can compile
3) use openblas instead of MKL

Now i have the issue #17. I will include my setup details in this issue number.

Many thanks for your help

**Comment by Seanny123** [comment] 2018-09-10 21:53
Despite compiling from source (Ubuntu 18.04), I am getting the same error. I understand a `conda` install may resolve these problems, which is currently being developed on the `conda_install` branch and am deeply grateful for your hard work. If there's any way I can assist, such as testing new builds, please let me know.

**Comment by rmrao** [comment] 2018-09-11 02:43
@Seanny123 you're getting the undefined symbol issue even when compiling from source and using `git submodule init` and `git submodule update` to get the FAISS repo? That's definitely odd - are you sure there isn't a separate version of FAISS somewhere else on your path that's being loaded?

**Comment by Seanny123** [comment] 2018-09-11 02:46
I think this is highly probable. I'm gonna spin up another non-conda EC2 instance tomorrow, which will probably resolve my problem.

**Comment by jeu1987** [comment] 2018-09-22 09:53
It seems I cannot get tsne-cuda to work. I'm getting the undefined symbol error _ZN5faiss14FaissExcepttionC1ERKSsPKcS4_i on running:

from tsnecuda import TSNE
X_embedded = TSNE(n_components=2, perplexity=15, learning_rate=10).fit_transform(X)

After building from source with:

cmake .. -DBUILD_PYTHON=TRUE -DWITH_ZMQ=FALSE -DBUILD_TEST=FALSE


OS: Ubuntu 18.04
python: 3.6 | Anaconda 5.2
gcc: 6.40
CUDA: 9.0

ldd -r libtsnecuda.so:

	linux-vdso.so.1 (0x00007ffc177e2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f64ad088000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f64ace84000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f64acc7c000)
	libfaiss.so => /usr/local/lib/libfaiss.so (0x00007f64ac984000)
	libcublas.so.9.0 => /usr/local/cuda-9.0/lib64/libcublas.so.9.0 (0x00007f64a8d07000)
	libcusparse.so.9.0 => /usr/local/cuda-9.0/lib64/libcusparse.so.9.0 (0x00007f64a55a1000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f64a5218000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f64a4e7a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f64a4c62000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f64a4871000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f64aef85000)
	libopenblas.so.0 => /usr/lib/x86_64-linux-gnu/libopenblas.so.0 (0x00007f64a25cb000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f64a239c000)
	libgfortran.so.4 => /usr/lib/x86_64-linux-gnu/libgfortran.so.4 (0x00007f64a1fbd000)
	libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f64a1d7d000)

Any suggestions would be greatly appreciated!

**Comment by DavidMChan** [comment] 2018-10-04 16:47
We just added conda support. You should be able to download with `conda install tsnecuda -c cannylab`, assuming you have CUDA 9.0 installed. Hopefully this fixes your compilation issues.

**Comment by cmartinezfleites** [comment] 2018-10-04 18:52
Great news to be able to install with conda! thank you for this. The server I have access to has CUDA 9.1, is it known if it works with this CUDA version? i tried and I got:
-bash-4.2$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tsnecuda import TSNE
>>> import numpy as np
>>> X = np.random.random((5000, 50))
>>> TSNE(verbose=1).fit_transform(X)
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: invalid device function
Aborted (core dumped)

My CUDA version is: Cuda compilation tools, release 9.1, V9.1.85

In my case, I am not allowed to change this CUDA version. Alternatively, is there a plan to release versions for other CUDA versions?

**Comment by rmrao** [comment] 2018-10-04 18:57
Yes, I’m working on trying to upload CUDA 8.0 and CUDA 9.1 versions. Anaconda is confusing so it might take a bit but we should have them up soon. 

Incidentally, are you not allowed to change the default CUDA version, or are you not allowed to install anything on the server? If it’s just the former, then you can install CUDA 9.0 and just prepend the path (usually /usr/local/cuda-9.0/lib64) to your LD_LIBRARY_PATH. Depending on the server set up, it might already have cuda-9.0 installed, because people sometimes don’t delete previous versions when they upgrade. If this is the case, you should be able to use this as a temporary work-around until we manage to upload the different versions.

**Comment by cmartinezfleites** [comment] 2018-10-04 19:12
I will check if there are older CUDA versions left so i can use them. I am
not allowed root access, so as far as i understand, i can install CUDA
version 9.0 locally but it wont work at runtime.

**Comment by rmrao** [comment] 2018-10-05 03:45
Just added CUDA 8.0 and 9.1 versions to conda. You can install the 9.1 binary with 

```
conda install tsnecuda cuda91 -c cannylab -c numba
```

If you have any problems with the binary, please open a new issue - I'm going to close this one since hopefully the pre-compiled binaries will solve peoples' problems with FAISS.

**Closed by rmrao** 2018-10-05 03:45 UTC

**Comment by zhanwenchen** [comment] 2024-06-10 23:56
You can see if your symbols are defined with

```bash
ldd -r ${CONDA_PREFIX}/lib/python3.12/site-packages/cv2/cv2.abi3.so # Check to see symbols are defined
```

If you see a bunch of undefined symbols, you may need to build again with your conda env path specified:

```bash
# OpenCV with CUDA support and system ffmpeg
cd && git clone --recursive https://github.com/opencv/opencv-python.git && cd opencv-python
git submodule sync
git submodule update --init --recursive
export CMAKE_ARGS="-DCMAKE_BUILD_TYPE=RELEASE -DWITH_CUBLAS=1 -DWITH_CUDA=ON -DWITH_NVCUVID=ON -DWITH_CUDNN=ON -DOPENCV_DNN_CUDA=ON -DCUDA_ARCH_BIN=7.0 -DOPENCV_ENABLE_NONFREE=ON -DENABLE_FAST_MATH=1 -DCUDA_FAST_MATH=1 -DOPENCV_EXTRA_MODULES_PATH=${HOME}/opencv-python/opencv_contrib/modules -DCUDA_CUDA_LIBRARY=/lib/x86_64-linux-gnu/libcuda.so -DCUDA_nvidia-encode_LIBRARY=/usr/local/cuda-12.4/targets/x86_64-linux/lib/libnvidia-encode.so -DPYTHON3_LIBRARY=${CONDA_PREFIX}/lib/libpython3.12.so -DPYTHON3_INCLUDE_DIR=${CONDA_PREFIX}/include/python3.12 -DPYTHON3_EXECUTABLE=${CONDA_PREFIX}/bin/python -DPYTHON3_PACKAGES_PATH=${CONDA_PREFIX}/lib/python3.12/site-packages"
sudo ln -s ${CONDA_PREFIX}/lib/python3.12/site-packages/numpy/core/include/numpy /usr/include/numpy
export ENABLE_HEADLESS=1
export ENABLE_CONTRIB=1
# TODO: remove the version number for setuptools in project.toml
scp ${HOME}/Downloads/Video_Codec_SDK_12.0.16/{Interface/nvEncodeAPI.h,Lib/linux/stubs/x86_64/libnvcuvid.so,Lib/linux/stubs/x86_64/libnvidia-encode.so} my_ec2:~ # NOTE: on laptop
sudo mv ~/nvEncodeAPI.h /usr/local/cuda/include
sudo mv ~/{libnvcuvid.so,libnvidia-encode.so} /usr/local/cuda/lib64
pip wheel . --verbose | tee install_opencv.log
pip install opencv_contrib_python_headless-*.whl
```
